### PR TITLE
DBforBix as Zabbix Proxy

### PR DESCRIPTION
**Pull request by vagabondan**
Hi Andrea, I have prepared my modifications for you to consider insertion to the main stream. Looking forward to hearing from you :)

### CODE REVIEW

**Comment by smartmarmot** [comment]
Hi Andrey,
There is still one thing that is not clear. Why you would like to implement the proxy instead of the Zabbix Active Agent?
What is included of your feature list here? 
I think that ZabbixSender.java has a logical error in the finally section don't contain the I/O handling code but only the persistent= false:
		finally{
                persistent = false;
Also from where are you getting the queries?

**Comment by vagabondan** [comment]
Active Agent has to know host names which it is serving. How will DBforBix get all host names for monitoring? To add new host for monitoring you should modify the configuration file of DBforBix what is not very convenient.
In case of Zabbix Proxy, DBforBix gets all hosts which are monitored via DBforBix Proxy and all complementary data for them.

I/O is handled in separate functions under Config class. They have to return error in case of problem with Zabbix Server connection. I'll check it.

Queries are retreived in the following way:
0. DBforBix sends configuration request for given Zabbix Proxy name just like an ordinary Zabbix Proxy. Zabbix Server sends all configuration data for appropriate Zabbix Proxy name: hosts, their items, keys, macro, etc.
1. DBforBix looks for all keys ending with .*DBforBix.config[<someid>,<DB_name_or_macro>] in the response of Zabbix Server. These keys should appear in agent type DB monitor to keep the field SQL query.
2. For each key found, DBforBix parse its SQL query field as an XML document. It contains item config in XML format, where queries, multiqueries are described.
3. Schedulers execute appropriate requests and save results to sender queue
4. Sender sends data to Zabbix Server, where appropriate items of type trapper should be defined.

**Comment by smartmarmot** [comment]
I see now the reason on the back of the choice. I need to say that it is a great idea! I'll check the code if I can spot issues but it looks good.

**Comment by vagabondan** [comment]
Ok, thank you. I forgot to add zabbix templates to commit... I create new pull request with them.

**Comment by alandba** [comment]
Hi,
Is this  proxy functionality already usable?

**Comment by vagabondan** [comment]
Hi!
Yes, of course. We monitor 80% of our databases by this tool.

**Comment by alandba** [comment]
Sorry if i am writing on the wronk place, but a didn't find how to send a private message. I'am  new to git and to developer world.
I would like to help developing this tool. how can I help ?
I also have a doubt how the new config works...does the old xml query file should be put on only one item with key .*DB4bix.config? Or only the xml portion for one query should be put in several items, in SQL query field?

**Comment by smartmarmot** [comment]
Don't worry for posting here it's ok.
The new sw has been mainly developed by vagabondan and he started with a brand new project called db4bix, and there are still some adjustment to make anyway the current sw is working well. If you're looking for the old sw I have a branch called "unstable" I know that is not the best name ever but I created on the fly in order to accept all the pull requests.
That said I still have to fix the persistence database as I didn't had any time so far but the current version is ok.

**Comment by vagabondan** [comment]
> does the old xml query file should be put on only one item with key .*DB4bix.config?

Each item with this suffix (or you can specify any other config suffix in DBforBix local config file as you wish) will be considered as DBforBix config, of course, if host, containing it, is marked to be monitored via Zabbix Proxy used by DBforBix.
You can place there full XML config with root element - parms.
Here the short example of working config that is situated in SQL field of discovery item with key oracle.discovery.DB4bix.config[instanceid,{$DSN}] ({$DSN} here is usual usermacro containing DSN for database, which you've described in local DBforBix config file):

`
<parms type="oracle" prefix="oracle.">
  <server>
            <discovery time="120" item="discovery.DB4bix.config[instanceid,{$DSN}]" names="INST_ID">SELECT inst_id FROM gv$instance</discovery>
            <query time="60" item="stats[%1,%2]">
		SELECT inst_id, REPLACE(name,' ','_'), value FROM gv$sysstat WHERE name IN ('user I/O wait time','physical read total bytes','physical write total bytes','lob reads','lob writes','db block changes','db block gets','consistent gets','physical reads','physical reads direct','physical writes direct','redo writes','physical read requests optimized','physical write requests optimized')
            </query>
      </server>
</parms>               
`

You can make it so complex as you wish. DBforBix creates separate thread to serve every single config item to avoid mutual influence of different config items.
But do not forget to create items - receivers of data. For config item above you should create item prototypes with keys:
oracle.stats[{#INST_ID},user_I/O_wait_time]
oracle.stats[{#INST_ID},physical_read_total_bytes]
...
oracle.stats[{#INST_ID},physical_write_requests_optimized]

For more information, please see Zabbix templates for DBforBix.

**Pull request merged**
